from components.core.clean_text import SelectedPreviousData
data = {
    "user_query": "are they avaiable from may 16 2026 to next 15 day",
    "prev_info": "user_query: hi\nresponse: \"<p>Hello! How can I assist you with Joy Beach Villas or The View Villa today?</p>\"\nuser_query: how many villa are there\nresponse: \"<p>There are 13 villas at Joy Beach Villas:</p> <ul> <li>Beachfront Villa</li> <li>Deluxe Garden Villa</li> <li>Garden Villa 1</li> <li>Garden Villa 2</li> <li>Garden Villa 3</li> <li>Garden Villa 4</li> <li>Garden Villa 5</li> <li>Garden Pool Villa 1</li> <li>Garden Pool Villa 2</li> <li>Garden Pool Villa 3</li> <li>Garden Pool Villa 4</li> <li>Garden Pool Villa 5</li> <li>Garden Pool Villa 6</li> </ul>\"\nuser_query: give there price\nresponse: \"<ul> <li>Beachfront Villa: 11,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Beachfront Villa/334679\" target=\"_blank\">View Villa</a></li> <li>Deluxe Garden Villa: 14,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Deluxe Garden Villa/336039\" target=\"_blank\">View Villa</a></li> <li>Garden Villa 1: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Villa 1/336040\" target=\"_blank\">View Villa</a></li> <li>Garden Villa 2: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Villa 2/342568\" target=\"_blank\">View Villa</a></li> <li>Garden Villa 3: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Villa 3/342569\" target=\"_blank\">View Villa</a></li> <li>Garden Villa 4: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Villa 4/342570\" target=\"_blank\">View Villa</a></li> <li>Garden Villa 5: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Villa 5/342571\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 1: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 1/352148\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 2: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 2/352154\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 3: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 3/352156\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 4: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 4/352157\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 5: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 5/363730\" target=\"_blank\">View Villa</a></li> <li>Garden Pool Villa 6: 9,000 THB per night <a href=\"https://armaitoly-website.vercel.app/property/Garden Pool Villa 6/363731\" target=\"_blank\">View Villa</a></li> </ul> <span>No per person tax is applied. For more details, contact reception@joybeachvillas.com or WhatsApp +66 62 4080324.</span>\""
}

previous_info = data['prev_info']

data = SelectedPreviousData(prev_info=previous_info)

print(len(data))


